config/routes.rb
Rails.application.routes.draw do
  resources :candidates do
    member do 
      post :vote
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidate.rb
class Candidate < ApplicationRecord
    validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController

    def index
        @candidates = Candidate.all
    end
    def show
        @candidate = Candidate.find_by(id: params[:id])
    end
    def edit
        @candidate = Candidate.find_by(id: params[:id])
    end

    def new
       @candidate = Candidate.new
    end

    def create
       
        @candidate = Candidate.new(candidate_params)

        if @candidate.save
          flash[:notice] = "Candidate created!"
          redirect_to '/candidates'
        else
          render :new    
        end    
    end
    def update
        @candidate = Candidate.find_by(id: params[:id])

        if @candidate.update(candidate_params)
            flash[:notice] = "Candidate created!"
            redirect_to '/candidates'
        else
            render :edit    
        end  
    end
    def destroy
        @candidate = Candidate.find_by(id: params[:id])
        @candidate.destroy

          flash[:notice] = "Candidate deleted!"
          redirect_to '/candidates'
    end

    def vote
        @candidate = Candidate.find_by(id: params[:id])
        @candidate.increment(:votes)
        @candidate.save
        
        flash[:notice] = "vote!"
        redirect_to '/candidates'
    end


    private
    def candidate_params
    clean_params =params.require(:candidate).permit(:name, :party,:age,:politics)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/views/candidates/edit.html.erb
<h1>Edit Candidates</h1>

<% if @candidate.errors.any? %>
<ul>
    <% @candidate.errors.full_messages.each do |mess| %> 
    <li><%= mess  %> </li>
    <% end %>
</ul>
<% end %>

<%= form_for(@candidate) do |form| %>
<div>
    <%= form.label:name %>
    <%= form.text_field :name %>
</div>
<div>
    <%= form.label:party %>
    <%= form.text_field :party %>
    
</div>
<div>
    <%= form.label:age %>
    <%= form.text_field :age %>
</div>
<div>
    <%= form.label:politics %>
    <%= form.text_area :politics %>
</div>

    <%= form.submit%>

<% end %>

app/views/candidates/index.html.erb
<%= flash[:notice] %>

<h1>Hi</h1>


<%= link_to 'Add Candidate', new_candidate_path %>
<table>
    <tr>
        <td></td>
        <td>Votes</td>
        <td>Name</td>
        <td>Party</td>
        <td>Age</td>
        <td>Action</td>
    </tr>

    <% @candidates.each do |candidate| %>
    <tr>
        <td><%= link_to 'vote', vote_candidate_path(candidate.id), method: 'post' %></a></td>
        <td><%= candidate.votes %></td>
        <td><%= link_to candidate.name, candidate_path(candidate.id) %></a></td>
        <td><%= candidate.name %></a></td>
        <td><%= candidate.party %></td>
        <td><%= candidate.age %></td>

        <td><%= link_to 'update', edit_candidate_path(candidate.id) %>
            <%= link_to 'delete', candidate_path(candidate.id), method: 'delete', data: {confirm: 'are you sure'} %>
        </td>
    </tr>
    <% end %>
</table>

app/views/candidates/new.html.erb
<h1>hello</h1>

<% if @candidate.errors.any? %>
<ul>
    <% @candidate.errors.full_messages.each do |mess| %> 
    <li><%= mess  %> </li>
    <% end %>
</ul>
<% end %>

<%= form_for(@candidate) do |form| %>
<div>
    <%= form.label:name %>
    <%= form.text_field :name %>
</div>
<div>
    <%= form.label:party %>
    <%= form.text_field :party %>
    
</div>
<div>
    <%= form.label:age %>
    <%= form.text_field :age %>
</div>
<div>
    <%= form.label:politics %>
    <%= form.text_area :politics %>
</div>

    <%= form.submit%>

<% end %>

app/views/candidates/show.html.erb
<% if @candidate %>
<h1><%= @candidate.name %></h1>

<ul>
    <li>party: <%= @candidate.party %></li>
    <li>age: <%= @candidate.age %></li>
    <li>politics: <%= @candidate.politics %></li>
</ul>

<% else %>
<h1> No Record found!</h1>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VoteMem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>